name: shell commands

on: [push]

jobs:
  run-shell-command:

   runs-on: ubuntu-latest
   steps:
     - name: echo a string
       run: echo "test github actions workflows"
     - name: multiline script
       run: |
         node -v
         pwd
         npm install -g bats
         bats -v 

     - name: actions checkout
       uses: actions/checkout@v2
     - name: actions setup
       uses: actions/setup-node@v2
       with:
         node-version: '14'
    
    

       
    
          
          
